#!/bin/sh
if [ -e /lib/libgpiommap.a ]
then
	gcc src/main.c src/mdio.c src/cmdline.c /lib/libgpiommap.a -o main
else
	echo --------------------------------------------------------
	echo Error :First build libgpiommap.a
	echo git clone https://github.com/df3xc/BeagleBone-GPIO.git
	echo --------------------------------------------------------
fi


